//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mastersign.DashOps.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mastersign.DashOps.Properties.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit DashOps ähnelt.
        /// </summary>
        public static string Application_Exit {
            get {
                return ResourceManager.GetString("Application_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Project ähnelt.
        /// </summary>
        public static string Command_EditProject {
            get {
                return ResourceManager.GetString("Command_EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch Perspective ähnelt.
        /// </summary>
        public static string Command_SwitchPerspective {
            get {
                return ResourceManager.GetString("Command_SwitchPerspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command line: DashOps.exe [Options] [&lt;Project File&gt;]
        ///
        ///Options:
        ///-?, -h, /?, --help
        ///    Show this command line help.
        ///-p, --preserve-working-dir
        ///    Do not change the working directory to the project files parent directory. ähnelt.
        /// </summary>
        public static string CommandLine_Help {
            get {
                return ResourceManager.GetString("CommandLine_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid command line arguments:
        ///
        ///{0} ähnelt.
        /// </summary>
        public static string CommandLine_InvalidArguments {
            get {
                return ResourceManager.GetString("CommandLine_InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only one positional argument is allowed. ähnelt.
        /// </summary>
        public static string CommandLine_MultiplePositionals {
            get {
                return ResourceManager.GetString("CommandLine_MultiplePositionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command Line Arguments ähnelt.
        /// </summary>
        public static string CommandLine_Title {
            get {
                return ResourceManager.GetString("CommandLine_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DashOps - {0} - Editor ähnelt.
        /// </summary>
        public static string EditorTitle_1 {
            get {
                return ResourceManager.GetString("EditorTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format ähnelt.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred while loading the project file:
        ///
        ///{0} ähnelt.
        /// </summary>
        public static string LoadProject_Error_1 {
            get {
                return ResourceManager.GetString("LoadProject_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project file &apos;{0}&apos; could not be found. ähnelt.
        /// </summary>
        public static string LoadProject_FileNotFound_1 {
            get {
                return ResourceManager.GetString("LoadProject_FileNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading the project failed.
        ///
        ///{0} ähnelt.
        /// </summary>
        public static string LoadProject_LoadFailed_1 {
            get {
                return ResourceManager.GetString("LoadProject_LoadFailed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No project file given as command line argument and no default project file in the current working directory or in the user profile.
        ///
        ///{0}
        ///
        ///Would you like to create a default DashOps file in the user profiles document folder? ähnelt.
        /// </summary>
        public static string LoadProject_NoProject_1 {
            get {
                return ResourceManager.GetString("LoadProject_NoProject_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading DashOps Project File ähnelt.
        /// </summary>
        public static string LoadProject_Title {
            get {
                return ResourceManager.GetString("LoadProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The format version of the project is not supported.
        ///
        ///Application Version: {0}
        ///File Version: {1} ähnelt.
        /// </summary>
        public static string LoadProject_UnsupportedVersion_2 {
            get {
                return ResourceManager.GetString("LoadProject_UnsupportedVersion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string MessageBox_Cancel {
            get {
                return ResourceManager.GetString("MessageBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string MessageBox_No {
            get {
                return ResourceManager.GetString("MessageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string MessageBox_OK {
            get {
                return ResourceManager.GetString("MessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string MessageBox_Yes {
            get {
                return ResourceManager.GetString("MessageBox_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string Page_About_Title {
            get {
                return ResourceManager.GetString("Page_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string Page_Home_Title {
            get {
                return ResourceManager.GetString("Page_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dashboard ähnelt.
        /// </summary>
        public static string Page_Main_Title {
            get {
                return ResourceManager.GetString("Page_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The WebView2 runtime is required for the internal editor, but is not installed on this system.
        ///You can download the installer from the following link: ähnelt.
        /// </summary>
        public static string WebView2_NotFound {
            get {
                return ResourceManager.GetString("WebView2_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebView2 Runtime Unavailable ähnelt.
        /// </summary>
        public static string WebView2_NotFound_Title {
            get {
                return ResourceManager.GetString("WebView2_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DashOps ähnelt.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
