//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mastersign.DashOps.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoControl() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mastersign.DashOps.Properties.Resources.InfoControl", typeof(InfoControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active: ähnelt.
        /// </summary>
        public static string Active_Caption {
            get {
                return ResourceManager.GetString("Active_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arguments: ähnelt.
        /// </summary>
        public static string Arguments_Caption {
            get {
                return ResourceManager.GetString("Arguments_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command: ähnelt.
        /// </summary>
        public static string Command_Caption {
            get {
                return ResourceManager.GetString("Command_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID: ähnelt.
        /// </summary>
        public static string CommandId_Caption {
            get {
                return ResourceManager.GetString("CommandId_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command Monitor ähnelt.
        /// </summary>
        public static string CommandMonitor {
            get {
                return ResourceManager.GetString("CommandMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success Exit Codes: ähnelt.
        /// </summary>
        public static string ExitCodes_Caption {
            get {
                return ResourceManager.GetString("ExitCodes_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Facets ähnelt.
        /// </summary>
        public static string Facets_Empty_Hint {
            get {
                return ResourceManager.GetString("Facets_Empty_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Facets ähnelt.
        /// </summary>
        public static string Facets_Title {
            get {
                return ResourceManager.GetString("Facets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Headers: ähnelt.
        /// </summary>
        public static string HttpHeaders_Caption {
            get {
                return ResourceManager.GetString("HttpHeaders_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success Status Codes: ähnelt.
        /// </summary>
        public static string HttpStatusCodes_Caption {
            get {
                return ResourceManager.GetString("HttpStatusCodes_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timeout: ähnelt.
        /// </summary>
        public static string HttpTimeout_Caption {
            get {
                return ResourceManager.GetString("HttpTimeout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interval: ähnelt.
        /// </summary>
        public static string Interval_Caption {
            get {
                return ResourceManager.GetString("Interval_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging: ähnelt.
        /// </summary>
        public static string Logging_Caption {
            get {
                return ResourceManager.GetString("Logging_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patterns: ähnelt.
        /// </summary>
        public static string Patterns_Caption {
            get {
                return ResourceManager.GetString("Patterns_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected Certificate: ähnelt.
        /// </summary>
        public static string ServerCertificateHash_Caption {
            get {
                return ResourceManager.GetString("ServerCertificateHash_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Tags ähnelt.
        /// </summary>
        public static string Tags_Empty_Hint {
            get {
                return ResourceManager.GetString("Tags_Empty_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags ähnelt.
        /// </summary>
        public static string Tags_Title {
            get {
                return ResourceManager.GetString("Tags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title: ähnelt.
        /// </summary>
        public static string Title_Caption {
            get {
                return ResourceManager.GetString("Title_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TLS Verify: ähnelt.
        /// </summary>
        public static string TlsVerify_Caption {
            get {
                return ResourceManager.GetString("TlsVerify_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL: ähnelt.
        /// </summary>
        public static string Url_Caption {
            get {
                return ResourceManager.GetString("Url_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP Monitor ähnelt.
        /// </summary>
        public static string WebMonitor {
            get {
                return ResourceManager.GetString("WebMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working Directory: ähnelt.
        /// </summary>
        public static string WorkingDirectory_Caption {
            get {
                return ResourceManager.GetString("WorkingDirectory_Caption", resourceCulture);
            }
        }
    }
}
